enum ApplicationEvents {
  USER_SIGN_UP = 'USER_SIGN_UP',
  USER_LOG_IN = 'USER_LOG_IN',
  USER_RESET_PASSWORD_REQUEST = 'USER_RESET_PASSWORD_REQUEST',
  USER_RESET_PASSWORD = 'USER_RESET_PASSWORD',
  USER_UPDATED = 'USER_UPDATED',

  LOOK_CREATED = 'LOOK_CREATED',
  LOOK_UPDATED = 'LOOK_UPDATED',
  LOOK_DELETED = 'LOOK_DELETED',

  CLOSET_ITEM_CREATED = 'CLOSET_ITEM_CREATED',
  CLOSET_ITEM_UPDATED = 'CLOSET_ITEM_UPDATED',
  CLOSET_ITEM_DELETED = 'CLOSET_ITEM_DELETED',

  TAG_CREATED = 'TAG_CREATED',
  TAG_UPDATED = 'TAG_UPDATED',
  TAG_DELETED = 'TAG_DELETED',
}

export default ApplicationEvents;
